clone highlight without fsckObjects
due to::

  error: object 65b469a06de7ced74e32843ee262c7f1f92c4ab7: badTimezone: invalid author/committer line - bad time zone